export default {
    scIOType:{
        "读取":0,
        "写入":1
    },
    scType:{
      "文件":0,
      "数据库":1,
      "接口":2
    },
    scFileType:{
        "excel":0
    },
    scDbType:{
        "oracle":0,
        "sqlServer":1,
        "mysql":2
    },
    scApiType:{
      "post":"POST",
      "get":"Get"
    },
    scTypeName:{
        "excel":"excel",
        "oracle":"oracle",
        "sqlserver":"sqlserver",
        "mysql":"mysql",
        "api":"api"
    },
    btnType:{
        '添加':0,
        '修改':1,
        '无':2
    }

}
